name: Build
run-name: Build - ${{github.event.pull_request.head.ref}}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
jobs:
  linux-build-embedded:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/requirements.txt
      - name: Install compiler
        run: |
          sudo apt update
          sudo apt install gcc-arm-none-eabi
      - name: Run build script
        run: python tools/build.py -b Debug Release
